### ISSUE TITLE
Anki on aarch64 is terribly out of date

### ISSUE THREAD

**Issue by vxld100** [flathub/net.ankiweb.Anki#125]
The flathub website [claims](https://flathub.org/apps/net.ankiweb.Anki) that Anki is on version 23.10, however, this is only true for the x86 version. The aarch64 package is still on version 2.1.15, and hasn't been updated in 4 years! It is so out of date in fact, that it doesn't run properly in wayland, even when setting the appropriate environment variables. It just crashes, given that anki [supports wayland](https://docs.ankiweb.net/platform/linux/wayland.html) only since version 2.1.48. But even without these issues it doesn't work properly.

Please keep the aarch packages up to date.

**Comment by keftie22** [comment]
> The aarch64 refs should probably be yanked by an admin

Agreed. The page on Flathub is still advertising aarch64 support as well.

![image](https://github.com/flathub/net.ankiweb.Anki/assets/101351551/bb585e8d-5e6f-48b0-846b-49740f263301)

If it's not going to be supported and it's not going to be updated past that ancient version then it should just be pulled completely. It misleads users into thinking that they will get an up to date version until they actually open it.

**Comment by nehemiagurl** [comment]
This is still the case. KDE's Discover finds the old version perfectly fine (though installation fails),
![Screenshot_20240904_124514](https://github.com/user-attachments/assets/02d290cd-0947-461d-b82c-11681181bf06)
And it can also be found in the flatpak commandline (where installation actually succeeds):
`Name        Description                              Application ID          Version       Branch       Remotes
Anki        Powerful, intelligent flash cards        net.ankiweb.Anki        2.1.15        stable       flathub
`

**Comment by rayes0** [comment]
Currently only a cosmetic issue due to the old builds, which I cannot delete. ARM64 is not supported by the flatpak as Anki does not provide official builds. I am planning on building everything from source in the future which will solve this.

**Comment by federvieh** [comment]
@rayes0 If you need inspiration, you could take a look at https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/testing/anki

I think alpine is currently the only distro that ships anki as an up-to-date version for aarch64 (I'm the maintainer). I don't think it's too hard to get to work anymore (used to be much more complicated). Unfortunately, I can't really help with the flathub version, because I have no idea how flathub works. But if you have questions regarding the build procedure, don't hesitate to ask. :)

**Comment by nehemiagurl** [comment]
i think finding how to install is less of a problem (i used the [beta installation via pip and it worked great](https://betas.ankiweb.net/#via-pypipip)).
i think the problem is when you first go to try and find a version of anki for aarch64, you're extremely likely to encounter this flatpak and be under the impression it supports your system, when it doesn't. this is just another roadblock (and an unnecessary one) on the way to finding an install that actually works.

**Comment by rayes0** [comment]
The builds would need to be yanked by an flathub admin to not show on the website or installer. I unfortunately do not have access to them.

As for packaging, @federvieh the anki build itself is not particularly hard to do at least anymore, it is mainly the dependencies. Unlike packaging for a distro, in a flatpak I cannot simply list and install the python dependencies from other packages, I need to compile or grab them all manually. Which we can do, but previously there was no aarch64 builds for pyqt wheels on pypi, and nobody wanted to maintain builds for all the pyqt packages in addition to anki. Though I think there are aarch64 builds now, so this will be easier (I am planning on doing it sometime soon).

**Comment by rayes0** [comment]
https://github.com/flathub/net.ankiweb.Anki/pull/172 should be good for testing! Would be great if any aarch64 users could try the latest build from there and report if things are working properly.
