### ISSUE TITLE
The language setting doesnt work

### ISSUE THREAD

**Issue by haevalencia** [flathub/net.ankiweb.Anki#2]
After installing Anki and establishing a different language (eg. Spanish) and restarting, the interface is still displayed in English.

`org.kde.Platform/x86_64/5.9` and `org.kde.Platform.Locale/x86_64/5.9` are correctly installed (tested on fedora 27, Anki version 2.1.0beta37).

**Comment by kafran** [comment]
@jurf I don't know why you would want a Platform.Locale partially installed. Some apps tries to guess you locale and install it partially, probably to save space, I don't know. Most time I have to reinstall it completely. This shouldn't be your case then. Lets wait the maintainers =).

**Comment by jurf** [comment]
@kafran it’s not about apps guessing, Flatpak installs only the locales you need based on your system preferences – it’s built to work that way, so that you don’t have 60 locales installed lying around catching dust. If you need to install the full .Locale to get your language to work, you should report that ASAP.

I’m thinking about stepping up as the maintainer since this package has a lot of usability problems and is out of date. Do I understand that your install doesn’t have this issue?

**Comment by kafran** [comment]
@jurf owh, I see. Now I understand. I always need to install the full .Locale because I like to have the system in english (I prefer this for reading errors), but some apps I like to have in my language. So, flatpak always install the apps in english and I need to download the full .Locale to have Portuguese available.

Yes, I just installed Anki on a freshly installed Xubuntu 18.04 and everything works nice.

**Comment by jurf** [comment]
@kafran by ‘looking nice’ you mean you can choose Portuguese, or you use English?

**Comment by dsd** [comment]
I can reproduce this here, tested with:
1. Uninstall Anki
2. Remove Anki data dir
3. Change OS to Spanish and restart
4. Reinstall anki
5. Launch Anki
6. When prompted, select Spanish language

It still comes up in English.

Based on the above comments I was thinking the reinstall (after changing system language) would be necessary in order to make it not exclude Anki's spanish translations during installation. However upon running `flatpak run --command=/bin/bash net.ankiweb.Anki` I can see that _all_ language translations seem to be present in /app/share/anki/locale - not sure if that's a bug or just something I misunderstood from above?

And since the Spanish translation is definitely there either way, I'll have to look closer why it is not being activated.

**Comment by dsd** [comment]
Spotted it - `langDir` hardcodes /usr/share/anki/locale, need to make it respect the PREFIX passed at build time.

**Comment by jurf** [comment]
A simple `sed` should fix that.

**Comment by dsd** [comment]
It was fixed upstream in https://github.com/dae/anki/commit/57d7b1f54b2656f187ada3cf1a067b4da672307a.
I pushed v2.1.5 to fix this.
