### ISSUE TITLE
Apologies. This is being tracked upstream at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/709

### ISSUE THREAD

**Issue by aldevel** [flathub/net.ankiweb.Anki#21]
Hi,
if you meant "As this is an issue in a different component I'll close this here." as there is an other closed issue with the same title then I notice this as I have to name the title unique. Otherwise it shouldn't be a reason for closing issue, I think, especially if the problem is still persist. Please don't apologize, basically I got it free I mean, instead explain little bit more clear about the stuff you provided. I did the downgrade you mentioned however it didn't solve the issue. Other thoughts or explanation for the closed but referred issue below?
Thanks

Previously closed issue:

Apologies. This is being tracked upstream at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/709

For now you can downgrade the runtime:

flatpak update --commit=71faea5b07a69e755b0b3c3694aa5a8903d3a69b09994b0e8ebd8b60d2dc744f org.freedesktop.Platform.html5-codecs

As this is an issue in a different component I'll close this here.

_Originally posted by @nedrichards in https://github.com/flathub/net.ankiweb.Anki/issues/20#issuecomment-478012041_

**Comment by aldevel** [comment]
Ok, basically I don't know how but today it's started and it works now. I assume the right think to do if I close this now. Thanks for the previous reply.

**Comment by jurf** [comment]
Well, the problem was beyond our control, and affected many more apps, so there wasn’t much reason to keep an issue here.

The linked issue has since been fixed; that’s why it’s working again now.

However, next time please add a comment on the original issue if you have further questions, instead of opening a new one. You can add comments to closed issues too, we’ll still be notified.
