### ISSUE TITLE
[Request] Change to the qt6 build

### ISSUE THREAD

**Issue by Vitorvlv** [flathub/net.ankiweb.Anki#71]
Hi! I have a request, do you guys have any issues about using the qt6 build? It makes the experience on wayland a bit better.

**Comment by ingemarberg** [comment]
There were some cases of add-ons not working when Anki first switched to the Qt6 build. I'm not a big add-on user myself, so I either is fine for me. I tried the Qt6 build this morning and it seemed to work just fine on both X11 and Wayland. It would be great if you could try the test build in #72.

@rayes0 What do you think?

**Comment by Vitorvlv** [comment]
Gave it a spin, can confirm that it's working as expected.

All my addons worked fine. This is the ones i'm using:

![image](https://user-images.githubusercontent.com/26132870/175832965-af22b9ef-bd16-49bb-bd15-b42bfe0aa97d.png)

Image occlusion and Review Heatmap had some issues when anki first released the qt6 build, but since them they have been updated to work with it.

**Comment by rayes0** [comment]
I think it's a good idea to switch. Most nontrivial addons that are popular should be updated to work by now.

However, some older addons still don't work, some users might still want qt5, and anki still distributes both qt5 and qt6 builds, so I think it is still a good idea to also package a qt5 build.

I'm not sure how to go about doing this though. AFAIK flathub only supports beta and stable release channels, and extension branches. If we can't make that work, then we could just switch to qt6 and have qt5 users stay on a lower version (which some users already do for older addons), but that's not the optimal solution. I don't think it's fair for qt5 users to have to use a lower version just for this, especially when anki still officially distributes qt5 newer versions.

**Comment by Vitorvlv** [comment]
Would uploading the qt5 version as a separate app to flathub be an acceptable solution? Then we would have Anki and Anki Qt5.

**Comment by rayes0** [comment]
Yeah, that's how different editions of some Jetbrains IDEs are published. If we do that, we should probably rename the apps to net.ankiweb.Anki-Qt5 and net.ankiweb.Anki-Qt6 to distinguish them. Any thoughts, @ingemarberg?

**Comment by dsd** [comment]
I think you should keep the existing app name as is even if another one is introduced that uses qt5.

Can you share more details about the jetbrains example? https://flathub.org/apps/search/jetbrains are those the different editions?

**Comment by laolux** [comment]
I also think the regular net.ankiweb.Anki appname should be continued to be used. Otherwise users will not get automatic updates anymore and who knows after how many years they will check manually?

Breaking old extensions by switching to qt6 should be fine. Users will definitely notice this and then search online for the issue. Then they will discover the net.ankiweb.Anki-qt5 version (if it exists).
Old extensions not working with qt6 should not block the flatpak from transitioning to qt6. There might be new extensions which require qt6.

**Comment by rayes0** [comment]
> Can you share more details about the jetbrains example? https://flathub.org/apps/search/jetbrains are those the different editions?

IntelliJ IDEA is published as a community edition named [com.jetbrains.IntelliJ-IDEA-Community](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community), and an ultimate edition named [com.jetbrains.IntelliJ-IDEA-Ultimate](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate). Similarly with PyCharm, there is a [com.jetbrains.PyCharm-Community](https://github.com/flathub/com.jetbrains.PyCharm-Community) and a [com.jetbrains.PyCharm-Professional](https://github.com/flathub/com.jetbrains.PyCharm-Professional).

>I also think the regular net.ankiweb.Anki appname should be continued to be used. Otherwise users will not get automatic updates anymore and who knows after how many years they will check manually?

We can add an end of life warning to the current app (see https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life). It'll warn users when when they run flatpak and prompt them to switch to the new app name.

Though we should consult to Flathub admins about it. I can see some merits to keeping the original name as well.

**Comment by ingemarberg** [comment]
I agree that it would be preferable to keep using the existing app name. Since Qt6 seems to be the way forward – the native Apple Silicon build only provides a Qt6 version, for example – it seems reasonable for this Flatpak to switch to Qt6 and, at the same time, provide the Qt5 version as net.ankiweb.Anki-Qt5. 

We should, in my opinion, start by trying to get a separate Qt5 version published, as well as some notes about the different versions. When that is in place, I suggest that we change net.ankiweb.Anki to the Qt6 version.

**Comment by Vitorvlv** [comment]
Hi! Sorry to be that guy but any news on this? 

I've been using the test build from #72 on my laptop since it was made available, it's been working great, unfortunately I've recently tried to install it on my main pc and the repo is not available anymore, so that's why I'm asking.

**Comment by ingemarberg** [comment]
Once again, sorry for the lack of progress. I've not been feeling well for a long time.

Last night I built the most recent version of Anki and updated the Freedesktop runtime at the same time. I had various problems with the Qt5 version of Anki. The most obvious one was that the UI wasn't working properly. A blank page was shown instead of the deck screen. There were also other problems. Version 0.35 of mpv wouldn't work, for example.

The Qt6 version didn't have any of these problems, and thus this seems to be as good a time as any to change to Qt6. Please try the test build in #81 to make sure it's working properly for you as well. It seems to work fine for me using X11. I've also tested it briefly in Wayland.

**Comment by Vitorvlv** [comment]
> Once again, sorry for the lack of progress. I've not been feeling well for a long time.

I'm sorry to hear that, hope things get better soon!

> Please try the test build in https://github.com/flathub/net.ankiweb.Anki/pull/81 to make sure it's working properly for you as well.

At first glance everything seems fine, I'm on wayland. I'll use it for a few days and let you know if any issue pops up.

**Comment by Vitorvlv** [comment]
Haven't noticed any issues so far.

**Comment by ingemarberg** [comment]
@Vitorvlv Thank you for testing! I'll go ahead and merge the new build now.
